export enum SPentType {
  MATERIAL = 'MATERIAL',

  ADMINISTRATIVE = 'ADMINISTRATIVE',

  RENT = 'RENT',

  TELECOMMUNICATIONS_FEES = 'TELECOMMUNICATIONS_FEES',

  SERVICES = 'SERVICES',

  SHIFT = 'SHIFT',

  COMMUNICATION = 'COMMUNICATION',

  MARKETING = 'MARKETING',

  OTHERS = 'OTHERS',
}
