export enum StatusContract {
  ENCOURS = 'ENCOURS',

  RUPTURE_CONVENTIONNELLE = 'RUPTURE_CONVENTIONNELLE',

  LICENCIEMENT_ABUSIVE = 'LICENCIEMENT_ABUSIVE',

  LICENCIEMENT_ECONOMIQUE = 'LICENCIEMENT_ECONOMIQUE',

  FIN_CONTRAT = 'FIN_CONTRAT',
}
