export enum TypeAbsence {
  RTT = 'RTT',

  CONGES_PAYES = 'CONGES_PAYES',

  CONGES_SANS_SOLDE = 'CONGES_SANS_SOLDE',

  CONGE_MATERNITE = 'CONGE_MATERNITE',

  ABSENCE_INJUSTIFIE = 'ABSENCE_INJUSTIFIE',

  FORMATION = 'FORMATION',

  ACCIDENT_TRAVAIL = 'ACCIDENT_TRAVAIL',

  ABSENCE_EXCEPTIONNELLE = 'ABSENCE_EXCEPTIONNELLE',

  CONGES_PARTENITE = 'CONGES_PARTENITE',

  CHOMAGE_PARTIEL = 'CHOMAGE_PARTIEL',

  RECUPERATION = 'RECUPERATION',

  ARRET_MALADIE = 'ARRET_MALADIE',

  ABSENCE_JUSTIFIE = 'ABSENCE_JUSTIFIE',
}
